---
- name: Check Disk Space Usage
  hosts: "{{ host }}"
  tasks:
    - name: Disk usage from command module
      command: df -h
      register: space
    - name: Show disk usage
      debug:
        var: space.stdout_lines
...