---
- name: Install a program on a remote Linux machine
  hosts: "{{ host }}"
  become: yes 
  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes
  - name: Install package 
    apt:
      name: "{{ package }}"     
...