---
- name: Copy files from Local to Remote Windows host
  hosts: {{ host }}
  tasks:
    - name: Copy file with a playbook
      become: true 
      ansible.windows.win_copy:
        src: {{ src_file }}
        dest: {{ dest_folder }}
...