---
- name: Copy files from Local to Remote Non Windows host
  hosts: {{ host }}
  tasks:
    - name: Copy file with a playbook
      become: true 
      ansible.builtin.copy:
        src: {{ src_file }}
        dest: {{ dest_folder }}
...